logging:
  level:
    root: INFO
server:
  port : 8088
  servlet:
    context-path: /bank-challenge
---
spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    url: jdbc:postgresql://localhost:5432/bank?currentSchema=challenge
    username: postgres
    password: W4dm1n7z3o@#
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
  liquibase:
    enabled: false
spring-doc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /swagger-ui.html
